### ISSUE TITLE
Doesn't work with jasmine

### ISSUE THREAD

**Issue by toaster** [vandium-io/lambda-tester#11]
Hi, I tried the examples given in the documentation as well as the sample code in https://github.com/vandium-io/using-lambda-tester and failed to get it working with jasmine. It works well with mocha. But for reasons (personal preference indeed ;)) I want to use jasmine.

I'm fairly new to unit testing with node.js . What can I do to get it working?
It seems that with 

```javascript
…
it('works', () => {
  return LambdaTester(myHandler).event({}).expectResult();
});
…
```

the handler doesn't even get called with jasmine.

**Comment by toaster** [comment]
With

```javascript
…
it('works', (done) => {
  return LambdaTester(myHandler).event({}).expectSucceed().verify(done);
});
…
```

the handler gets called but the test always succeeds even if the handler calls `callback('error')`.

**Comment by toaster** [comment]
My package versions:
* lambda-tester 2.7.0
* jasmine 2.5.3
* mocha 3.2.0

**Comment by toaster** [comment]
It seems that the `done` function of jasmine works different from the one of mocha. It does not take an argument but has the fail function as property. The following works with jasmine:
```javascript
…
it('works', (done) => {
  LambdaTester(myHandler).event({}).expectSucceed().then(done, done.fail);
});
…
```

**Comment by toaster** [comment]
I propose to replace `addLegecyVerify` in `index.js` by:
```javascript
// for v1 and jsamine users
function addVerify(promise) {
  promise.verify = function(done) {
    return promise.then(done, done.fail || done);
  };
}
```

And add the `verify` method to the expect promises where it is not yet added.

**Comment by richardhyatt** [comment]
looks like a good solution - I'll make the change and add some tests for it

**Comment by richardhyatt** [comment]
Have you looked at using [Jasmine Promises](https://github.com/matthewjh/jasmine-promises)?

**Comment by toaster** [comment]
Not yet, but I will. Thanks for the tip.
