### ISSUE TITLE
Node version check should not expect an exact version as the package requires

### ISSUE THREAD

**Issue by jdupl** [vandium-io/lambda-tester#13]
This lib works fine with nodejs 5.12. Seems like version 2.8.0 expects and exact version.
It should actually check for a range of version as the original issue #12 would suggests. Below node 7 should be fine.
The package specifies: 
```
  "engines": {
    "node": ">=4.3.2"
},
```
Here is the culprit: https://github.com/vandium-io/lambda-tester/blob/master/lib/index.js#L199

@ephelip @kiniamaro

**Comment by Kiniamaro** [comment]
@jdupl I made a Pull Request fixing this.

**Comment by richardhyatt** [comment]
Released patch in 2.8.1. Thanks @Kiniamaro @jdupl
