### ISSUE TITLE
No support for node 7.5

### ISSUE THREAD

**Issue by kylelaverty** [vandium-io/lambda-tester#15]
In my dev environment we are using the newer node 7.5 and I would really like this project to support that so I can continue to use it.

**Comment by kylelaverty** [comment]
I took another look and while locally we have 7.5 aws does not support it yet so I am closing this issue.

**Comment by dc00p** [comment]
We are deliberately only supporting version of Node.js used by AWS Lambda to keep environments consistent. For a convenient way of switching between versions of Node.js, checkout [Node Version Manager (NVM)](https://github.com/creationix/nvm).
