### ISSUE TITLE
Using alternate test .env

### ISSUE THREAD

**Issue by nonword** [vandium-io/lambda-tester#16]
Wonder if folks have recommendations for best way to bring in additional/alternate environmental variables. It's common to have a separate set of configs for running tests, but lambda-tester seems to only load `.env`.

Background: We use `node-lambda` to run and deploy our lambdas, which recommends placing env vars that one wants deployed in `deploy.env`. For example, we keep an encrypted db connection string in that file. In order to test our app's ability to decrypt that variable and connect to our db, we're currently manually loading `deploy.env` or `test.deploy.env`. This seems like it must be a common need, so I wonder if there's a more formal method of loading alternate (i.e. test) configs.

One way lambda-tester could formally support this would be to allow reading from an alternate env file path here:
https://github.com/vandium-io/lambda-tester/blob/master/lib/index.js#L526

Thanks!

**Comment by richardhyatt** [comment]
Do you want to propose a way to do this - i.e. should lambda-tester search for an env file that matches .env, deploy.env, test.deploy.env, etc or should we use environment variables/code to select it?

**Comment by nonword** [comment]
It's a good question. Most flexible would be to load by env variable, but perhaps there are emerging conventions we can rely on instead like - as you suggest - load .env, then deploy.env, then test.deploy.env in series. That would allow people to load deployable env vars first, then optionally override them with test.deploy.env.

I can put together a PR if that sounds sensible.

My only worry is that might be a cruel surprise when one's tests modify production database data. If one stores prod db creds in deploy.env like we do, one might not expect `npm test` to run with those creds..

**Comment by richardhyatt** [comment]
Thinking about adding support for a `.lambdatester` file that would allow the user to specify the appropriate `.env` file.

**Comment by richardhyatt** [comment]
Added support in version 3.0 - add a `.lambda-tester.json` file in the root of your project, add the `envFile` entry with the relative or absolute path of the `.env` file.
