### ISSUE TITLE
Is it possible to use async/await?

### ISSUE THREAD

**Issue by andrewoh531** [vandium-io/lambda-tester#21]
I had a quick look at the code and I'm assuming it's not possible in its current state since the verifier is passed in to the `expectResult` method. Is that right?

**Comment by dc00p** [comment]
For compatibility reasons we are not supporting async/await and other ES7 features until AWS Lambda rolls out support for Node.js version 7.  Once these features have been rolled out by AWS we will look at support for async/await.

**Comment by andrewoh531** [comment]
Ok no problem. Thanks for responding back.

**Comment by jamesdixon** [comment]
Hello, is this possible now that Lamda supports Node 8?

**Comment by ArcadeRenegade** [comment]
I keep getting Error: Promise.reject() called instead of Promise.resolve()
