### ISSUE TITLE
Remove Node version expectation

### ISSUE THREAD

**Issue by jawadst** [vandium-io/lambda-tester#24]
I understand that your goal is to match the version of node that is running on AWS but for people using transpilers (TypeScript, Babel, etc.), it'd be great to be able to run our tests in both our non-transpiled and our transpiled code. This is not currently possible because of the "node.js x.y is not currently supported, please test with an older version" message.

Currently, what we are forced to do is:
 - Have one set of tests that run against most our code in the non-transpiled version. Most of our code does not need to be run in Lambda tester and can be tested without it.
 - Run all the tests transpiled + an extra set of tests that only run in the transpiled version and that uses Lambda Tester to test the actual Lambdas themselves.

Could you remove that restriction? Potentially, make it a parameter where the default is the current behavior and developers can decide if they want to remove the restriction.

**Comment by richardhyatt** [comment]
Would an environment variable work to disable node version check - something like `LAMBDA_TESTER_NODE_VERSION_CHECK` set to `false`?

**Comment by jawadst** [comment]
Yes that'd work great as well

**Comment by richardhyatt** [comment]
Change is now available in the 3.x branch if you'd like to test out before we release 3.1
