### ISSUE TITLE
Version docs out of date

### ISSUE THREAD

**Issue by aadennis** [vandium-io/lambda-tester#25]
Hi 
Great framework - thanks!
Just calling out that I think the installation docs here are a little out of date with the facts:
"...lambda-tester by default will throw an exception if the version of node is not 4.3.2, ..."
As you know, your framework supports 6.10.* (i.e. since presumably AWS's own update) and even 7.0.0 I think.
_https://github.com/vandium-io/lambda-tester/blob/master/docs/installation.md_
Thanks

**Comment by richardhyatt** [comment]
thanks - fixed
