### ISSUE TITLE
fake environment variables?

### ISSUE THREAD

**Issue by fmielke** [vandium-io/lambda-tester#26]
hello,

i have environment variables defined in my lambda. the lambda only works if they are available, but if i use lambda-tester as is, there are no environment variables defined :/

how can i define environment variables for lambda-tester?

**Comment by richardhyatt** [comment]
There are several ways to do this:

1. Use a `.env` file to configure your environment variables (just don't deploy them!) - lambda-tester will automatically read this file. This file name can be changed using the configuration settings for lambda-tester outlined in the documentation
2. Use `dotenv` module and load the values from different stores
3. The vandium `env-restorer` module will snapshot and restore environment values between test scenarios in a more programmatic fashion - we use it for our tests

Let me know if this helps

**Comment by richardhyatt** [comment]
Was this issue resolved or do we need to add some additional functionality to the library?
