### ISSUE TITLE
Support node 8.10

### ISSUE THREAD

**Issue by Limess** [vandium-io/lambda-tester#32]
AWS [now supports node 8.10 on lambda](https://aws.amazon.com/blogs/compute/node-js-8-10-runtime-now-available-in-aws-lambda/).

Currently this library throws the following when testing on node 8.10:

```
Error: node.js 7.x is not currently supported, please test with an older version.
```

For now it is possible to bypass this with `LAMBDA_TESTER_NODE_VERSION_CHECK=false`

**Comment by nikhilkakade2108** [comment]
refer https://github.com/vandium-io/lambda-tester/blob/master/docs/node-version-verification.md

**Comment by richardhyatt** [comment]
Updated version number support to include `8.10.x`. Published in `3.3.0` release

**Comment by Limess** [comment]
Thanks for this!

**Comment by richardhyatt** [comment]
I'm planning on cleaning the code base up in a 4.0 release to better make better use of node 8
