### ISSUE TITLE
Support for node@8.10?

### ISSUE THREAD

**Issue by pedro-mass** [vandium-io/lambda-tester#35]
AWS Lambda now supports Node.js v8.10. It would be nice to have this testing tool bump up it's version number too.

Supporting docs:
- https://aws.amazon.com/about-aws/whats-new/2018/04/aws-lambda-supports-nodejs/
- https://aws.amazon.com/blogs/compute/node-js-8-10-runtime-now-available-in-aws-lambda/
- https://serverless.com/blog/aws-lambda-node-8-support-what-changes-serverless-developers/

**Comment by richardhyatt** [comment]
The tool supports node 8.10 but the docs require a fix. Will be updating the code that performs version checking

**Comment by paulihuhtiniemi** [comment]
Please also check `package.json` that still has this in 3.3.0 :)

```
  "engines": {
    "node": ">=6.0.0 <7.0.0"
  },
```

**Comment by dougmoscrop** [comment]
also wat

https://github.com/vandium-io/lambda-tester/blob/master/lib/index.js#L26

**Comment by LobeTia** [comment]
Hi! Any news on this? Using lambda-tester for 8.10 would be lovely

**Comment by richardhyatt** [comment]
pushing to npm today
