### ISSUE TITLE
No way to inject "context"

### ISSUE THREAD

**Issue by xsurfing** [vandium-io/lambda-tester#4]
Nice work! However I would like to add custom data to "context" to, for example, inject a Cognito identity.
Would recommend to add support for
.context(data)
which will basically amend context as created by createContext with all provided attributes.

**Comment by richardhyatt** [comment]
How about .clientContext() and .identify() to mirror context properties from the [Lambda documentation](http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html)?

**Comment by xsurfing** [comment]
Great, thx! (Sorry, was busy so far)
