### ISSUE TITLE
Node.js version supports for lambda and codebuild

### ISSUE THREAD

**Issue by GeorgeBell1982** [vandium-io/lambda-tester#40]
Hi, In AWS CodeBuild there is either a node version 6.3 or a 8.11 which can be selected, and by chance this is exactly on the opposite sides of your version check. Would you be able to update it to 8.11?

Edit: I have for now disabled the version check with your environment variable LAMBDA_TESTER_NODE_VERSION_CHECK=false, not necessarily the best practice

**Comment by richardhyatt** [comment]
Added into 3.5.0 release
