### ISSUE TITLE
Not able to run test on node version 9.4.0

### ISSUE THREAD

**Issue by brijeshprasad89** [vandium-io/lambda-tester#45]
I am having node version 9.4.0. And I am using lamda-tester of version 3.5.0

According to documentation, version 3.5.0 is supported for node version >=8.10.0.

On running the tests with above environments I get this error
`Error: Please test with node.js versions: 8.10.0 - 8.999.0`

**Comment by cameck** [comment]
The docs do say that... But I would strongly suggest sticking to the supported runtimes, to ensure as much parity as possibly. 8.10 or 6.10 are the supported node runtimes in aws lambda --  https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html.

**Comment by KHodderDVSA** [comment]
AWS supports Node 10.x now. 
https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

**Comment by ThomasVuillaume** [comment]
> 
> 
> AWS supports Node 10.x now.
> https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

Would be great to have this package compatible soon  !

**Comment by julianpellasrice** [comment]
@richardhyatt is it possible to get this looked at soon? I see there's already a PR that addresses node10 compatibility waiting for review/merge.

**Comment by richardhyatt** [comment]
Node 10 support added to 3.6.0 release
