### ISSUE TITLE
Support for Promises in handler

### ISSUE THREAD

**Issue by jtwebman** [vandium-io/lambda-tester#53]
AWS Lambda supports returning a promise now not just calling the callback. Do you plan to support this with this library. Currently I get this error 
```
      Error: Promise.resolve() called instead of callback()
      at processOutcome (node_modules/lambda-tester/lib/runner.js:57:15)
      at Promise.resolve.then.then.then (node_modules/lambda-tester/lib/runner.js:277:26)
      at <anonymous>
```

**Comment by jtwebman** [comment]
Ok I found expectReject and expectResolve but I am going to keep the issue open and open a PR to add this to the Readme so people know about it.

**Comment by richardhyatt** [comment]
Starting in version 4.0, `expectResult()` and `expectError()` will work for promises, callbacks and context.succeed/fail cases.
