### ISSUE TITLE
Failed assertion prevents 'done()' from being called

### ISSUE THREAD

**Issue by developmentalmadness** [vandium-io/lambda-tester#6]
The test below never finishes and just results in the test timing out with "Ensure the done() callback is being called in this test":

    'use strict';
    
    var chai = require('chai'),
        expect = chai.expect,
        LambdaTester = require('lambda-tester');
    
    describe("LambdaTester", function() {
        it("should return from async calls", function(done) {
            return LambdaTester(function(event, context, callback) {
                callback(null, { message: "I did nothing!" });
            })
            .event({ Records: [] })
            .expectResult(function(result) {
                expect(result.message).to.equal("I did it!");
                done();
            });
        })
    });

I'm running node v4.3.2 and here's my `package.json` file:

    {
      "name": "data-file-custodian",
      "version": "0.1.0",
      "scripts": {
        "test": "mocha"
      },
     "author": "Mark J. Miller",
     "devDependencies": {
        "chai": "^3.5.0",
        "lambda-tester": "^2.6.0",
        "mocha": "^3.0.2"
      },
      "dependencies": {
        "async": "^2.0.1",
        "aws-sdk": "^2.4.13",
        "debug": "^2.2.0",
        "lodash": "^4.14.2"
      }
    }
    
I would expect to see the failure message immediately instead of waiting for the timeout and not getting the failure message from `expect`.

**Comment by richardhyatt** [comment]
Remove `done` and the call to `done()` since you're returning the tester, which is a promise that mocha will resolve.

code should look like:

```js
'use strict';

var chai = require('chai'),
    expect = chai.expect,
    LambdaTester = require('lambda-tester');

describe("LambdaTester", function() {

    it("should return from async calls", function() {
       
         return LambdaTester(function(event, context, callback) {
            callback(null, { message: "I did nothing!" });
        })
        .event({ Records: [] })
        .expectResult(function(result) {
            expect(result.message).to.equal("I did it!");
        });
    })
});
```

**Comment by developmentalmadness** [comment]
Does that include tests which are themselves async? Like the following:

    'use strict';
    
    var chai = require('chai'),
        expect = chai.expect,
        LambdaTester = require('lambda-tester');
    
    describe("LambdaTester", function() {
    
        it("should return from async calls", function() {
    
             return LambdaTester(function(event, context, callback) {
                callback(null, { message: "I did nothing!" });
            })
            .event({ Records: [] })
            .expectResult(function(result) {
                callSomeServiceToVerify(result.message, function(err, data) {
                    expect(result.message).to.equal(data);
                });
            });
        })
    });

**Comment by richardhyatt** [comment]
Use promises for everything if you can - improves the readability and maintainability of your code for the long term. Here's a few options:

1. You can wrap the `callSomeServiceToVerify() in a Promise:

```js
    it("should return from async calls", function() {

         return LambdaTester(function(event, context, callback) {
            callback(null, { message: "I did nothing!" });
        })
        .event({ Records: [] })
        .expectResult(function(result) {
            return new Promise( function( resolve, reject ) {

                callSomeServiceToVerify( result.message, function( err, data ) {
                
                if( err ) {
                    return reject( err );
                }
              
                resolve( data );
             })
             .then( function( data ) {
                expect(result.message).to.equal(data);
            });
        });
    });
```

2. Use a library like [bluebird](http://bluebirdjs.com) and wrap `callSomeServiceToVerify()` using the `promisify()`

3. Write `callSomeServiceToVerify()` as a promise or write a wrapper for it:

```js
'use strict';

var chai = require('chai'),
    expect = chai.expect,
    LambdaTester = require('lambda-tester');

function callSomeServiceToVerifyAsync( message ) {

    return new Promise( function( resolve, reject ) {

        callSomeServiceToVerify( message, function( err, data ) {
                
            if( err ) {
                return reject( err );
            }
              
            resolve( data );
        });
    });
}

describe("LambdaTester", function() {

    it("should return from async calls", function() {

         return LambdaTester(function(event, context, callback) {
            callback(null, { message: "I did nothing!" });
        })
        .event({ Records: [] })
        .expectResult(function(result) {

            return callSomeServiceToVerifyAsync( result.message )
                     .then( function( data ) {
                         expect( result.message ).to.equal( data );
                     });
        });
    });
});
```

**Comment by developmentalmadness** [comment]
Thanks! That worked!
