### ISSUE TITLE
AWS api event source

### ISSUE THREAD

**Issue by adben** [vandium-io/lambda-tester#7]
Question: What are the best practices when testing AWS api events included in the handler logic?  Proxyquire?

**Comment by richardhyatt** [comment]
We use Proxyquire to stub out everything for unit testing - if you're interested, I can share some code that we use to unit test AWS services.

**Comment by adben** [comment]
Yes please!

**Comment by richardhyatt** [comment]
I created an example project for you - might not be 100% production ready but gives you an idea how to use proxyquire/sinon/lambda-tester together. Code is in the [examples/aws_service](https://github.com/vandium-io/lambda-tester/tree/master/examples/aws_service) directory.

**Comment by adben** [comment]
Thank you!

**Comment by richardhyatt** [comment]
ok to close the issue?

**Comment by adben** [comment]
Yes, thanks!
